### ISSUE TITLE
`getNodes` method on AbstractResponse

### ISSUE THREAD

**Issue by eapache** [Shopify/graphql_java_gen#11]
Currently if your schema has a node type we generate a `getNodes` helper method on all the classes that implement `AbstractResponse`. I've run into a case where I would like to have `getNodes` declared as an abstract method on `AbstractResponse`.

This isn't quite straightforward since `AbstractResponse` isn't generated so we can't just remove the method when there is no `Node` type. We could generate a bunch of empty implementations in that case but it's not ideal.

@dylanahsmith thoughts?

**Comment by dylanahsmith** [comment]
Should we add a Node interface to the graphql support package so that we can implement getNodes on `AbstractResponse` and have that implementation just return an empty array?  The generated code would then need to have the Node interface in the schema implement the Node interface from the support package.
