### ISSUE TITLE
Support for Jackson deserialization

### ISSUE THREAD

**Issue by bhumit** [Shopify/graphql_java_gen#34]
Currently the generated code does not support Jackson ser/der when using the generated schema in a Spring Boot project with Jackson. 
Jackson expects an empty constructor for the class. 

`org.codehaus.jackson.map.JsonMappingException: No suitable constructor found for type`

Any plans to add empty constructor to the generated schema?

**Comment by bhumit** [comment]
@dylanahsmith any update on this?

**Comment by dylanahsmith** [comment]
I haven't been involved with this project lately, so I don't really have much context on how we are using it or the vision for it.

What is your use case?  Since the generated code is being used for deserialization, so the input to it is the serialized version of it.

It looks like AbstractResponse `implements Serializable` which could also be used for serialization.

**Comment by dylanahsmith** [comment]
It isn't clear why this is needed, so I'm going to close this
