### ISSUE TITLE
Please, how can I use it?

### ISSUE THREAD

**Issue by carloca68** [Shopify/graphql_java_gen#53]
Can't find the java lib versions on jcenter...

compile 'com.shopify.graphql.support:support:0.2.0'

The gem is outdated!!!!

do.rb:19:in `<main>': undefined method `save_granular' for #<GraphQLJavaGen:0x0000000006eca058> (NoMethodError)

Lost hours trying to follow the instructions to discover the versions are years outdated...

Please make it clear in your docs.

**Comment by dylanahsmith** [comment]
> do.rb:19:in `<main>': undefined method `save_granular' for #GraphQLJavaGen:0x0000000006eca058 (NoMethodError)

There hasn't been a release since this method was added.  See the docs for the released version: https://github.com/Shopify/graphql_java_gen/tree/v0.1.1

If you want to use an unreleased version, then you can use it through a git submodule (https://github.com/Shopify/graphql_java_gen/issues/50#issuecomment-585931652)

**Comment by dylanahsmith** [comment]
> compile 'com.shopify.graphql.support:support:0.2.0'

Oh, looks this is from the README.  I'm not sure why that was bumped before a release.
